### PR TITLE
Fix compatibility marshmallow>=3.0.0b7

### PR DESCRIPTION
**Pull request by SBillion**
Make it work with last marshmallow prerealease which don't return a tuple data, errors anymore for load and dump

### CODE REVIEW

**Comment by jeremy303** [comment]
@sloria @SBillion 
Can get this be merged and a new package of flask-marshmallow be pushed to  PyPI?  We're running into this issue with a number of APIs and it would be great to avoid implementing work-arounds in all of them.

Thanks for the great work!

**Comment by sloria** [comment]
Sorry for the delay on this; been busy with work and lift this past month. I'll try to get to this over the weekend. Thanks @SBillion for the PR.

**Comment by jeremy303** [comment]
@sloria  Hate to put you to work over your weekend, but thanks so much!

**Comment by sloria** [comment]
Looks great! Thanks again @SBillion

**Comment by sloria** [comment]
This is released in 0.9.0.

**Pull request merged**
