### PR TITLE
fix: distutils deprecation warning in Python 3.10

### LINKED ISSUE #242: Python3.10: Distutils depreciation warning
Couldn't find an issue for this yet, but in py3.10 there's a warning about distutils. Should be an easy transition.

```
  /usr/local/lib/python3.10/site-packages/flask_marshmallow/__init__.py:10: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
```

### PR DESCRIPTION
**Pull request by GabrielLins64**
Fixes: #242 

Fixes the distutils deprecation warning by using packaging.version

### CODE REVIEW

**Comment by akiot-b** [comment]
What is the current status of this fix?

**Comment by garthk** [comment]
Build failure; build log long since gone. @GabrielLins64 are there any extra commits in `dev` you can merge in to have another try?

**Comment by GabrielLins64** [comment]
> Build failure; build log long since gone. @GabrielLins64 are there any extra commits in `dev` you can merge in to have another try?

I can't see any new changes since January. However, I can push some useless commit to give it another try.

**Comment by sirosen** [comment]
Thanks so much for taking care of this!
I'm closing this as I rebased-and-merged it in #253, but your work and citation in the changelog were preserved there. 😄 

I'm still working through things and getting ready for a release, but hopefully I'll be able to cut v0.15.0 shortly!

**Pull request closed without merging**
