### PR TITLE
add `__version__`

### PR DESCRIPTION
**Pull request by uncle-lv**
Sometimes we need get the current version.

### CODE REVIEW

**Comment by uncle-lv** [comment]
It's for [myself](https://github.com/apiflask/apiflask/pull/552#discussion_r1536640047). 😛

**Comment by greyli** [comment]
It is better to use [`importlib.metadata.version`](https://github.com/apiflask/apiflask/pull/552#discussion_r1536728037) if this project doesn't provide a `__version__` variable.

**Comment by uncle-lv** [comment]
> It is better to use [`importlib.metadata.version`](https://github.com/apiflask/apiflask/pull/552#discussion_r1536728037) if this project doesn't provide a `__version__` variable.

Yes! I have done it.

**Comment by uncle-lv** [comment]
It's not necessary to merge this pr now.

**Comment by sloria** [comment]
`__version__` was intentionally removed in https://github.com/marshmallow-code/flask-marshmallow/pull/284 to be in line with the best practice of using `importlib.metadata.version`. the pallets projects have done the same. so closing this for now!

**Pull request closed without merging**
